### ISSUE TITLE
bug report in WMMSE.py

### ISSUE THREAD

**Issue by scliubit** [hqyyqh888/DeepUnfolding_WMMSE#1]
hello, 
thanks for sharing your code.

i find that in your WMMSE.py file, the channel generation process has been wrongly written (line 48-59), but seems to have no effect in final result.

**Comment by YuxuanDuan** [comment]
Hello, @scliubit I think there must be some bugs in WMMSE.py because I found that the result of my implementation in matlab is much higher than this. Do you get this issue solved?

**Comment by scliubit** [comment]
I think the codes are just fine. I also came into some similar situation that matlab implementation sometimes shows higher performance, but the reason varies, e.g., the inversion operation in matlab shows different behavior. We can not discuss without your codes.

**Comment by YuxuanDuan** [comment]
> I think the codes are just fine. I also came into some similar situation that matlab implementation sometimes shows higher performance, but the reason varies, e.g., the inversion operation in matlab shows different behavior. We can not discuss without your codes.

Yes, However, the sum rate of the matlab implementation is almost twice higher than the result implemented in Python, which confuses me a lot. I can accept that they have a little gap, but the gap here is too huge I think. If it is convenient with you, would you like to see my codes and help me to see what goes wrong?
